### ISSUE TITLE
Consider moving this repository to the dedicated scaleway-community organization

### ISSUE THREAD

**Issue by moul** [scaleway-community/scaleway-serendipity#5]
Hey @onli, can you check out this thread on our community website: https://community.scaleway.com/t/how-to-distribute-or-share-an-image/1129/12

and tell me if you would like to move your repo so it's easier for us to help you maintain this image (especially for upgrades of the inherited ubuntu image), you will still be admin and the official maintainer of the project

**Comment by onli** [comment]
Sure, I'd absolutely be okay with that. I would transfer it via Github's settings to scaleway-community as an owner?

**Comment by moul** [comment]
I don't think we can do this because I will make you admin of the repo once moved

For now, the best solution I know is you transfer ownership to me: `moul`, then I transfer ownership to scaleway-community and add you as admin just after

**Comment by onli** [comment]
Okay. That collides with your existing image-app-serendipity-repo. Could you rename or translate that and ping me again?

**Comment by moul** [comment]
done, sorry :)

**Comment by onli** [comment]
Np. The transfer is requested.

**Comment by moul** [comment]
Repo moved here: https://github.com/scaleway-community/scaleway-serendipity
Invitation sent, you need to accept here: https://github.com/scaleway-community

**Comment by onli** [comment]
Done! Thanks, I'm happy you incorporate – dunno if that is the right word ;) – it.

**Comment by moul** [comment]
:)
